# configurations for only developers
spring.datasource.url=jdbc:mariadb://localhost:3306/clinica_db
spring.datasource.username=clinica_admin
spring.datasource.password=pamonha

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=ajasoftware_dev_secret_key_12345
api.security.cookie.secure=false

# Separate origins with a comma if there is more than one frontend (e.g., http://localhost:4200,https://mysystem.com)
api.cors.allowed-origins=http://localhost:4200